# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B7rCI0hpA1Ivxe0kIomRFAxSESwdG7st
"""

import pandas as pd
 df = pd.DataFrame({'Ism': ['Ilhom','Abdulbosit'],
                    'Familyasi' : ['Eshboyev', 'Turgunov'],
                      'Yoshi': ['20','19'],
                      'Guruh': ['611-23','611-23']
                    })
 print(df)